apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: example-job-container
          image: busybox
          args:
            - /bin/sh
            - -c
            - date; echo this is job example
      restartPolicy: Never