version: "3.8"
services:
  seata-server:
    image: seataio/seata-server:2.0.0
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - STORE_MODE=db
      # 以SEATA_IP作为host注册seata server
#      - SEATA_IP=seata_ip
      - SEATA_PORT=8091
    volumes:
      - ./conf/application.yml:/seata-server/resources/application.yml
networks:
  default:
    name: nacos-promethes_default
    external: true