version: "3"
services:
  seata-server:
    image: seataio/seata-server:2.0.0
    hostname: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file