# application.yml
server:
  port: 9001
# two groups, each has one master and two slaves
spring:
  shardingsphere:
    datasource:
      names: ds0, ds1, slave01, slave02, slave11, slave12
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db0?useSSL=false
        username: root
        password: root
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/db1?useSSL=false
        username: root
        password: root
      slave01:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/db0?useSSL=false
        username: root
        password: root
      slave02:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/db0?useSSL=false
        username: root
        password: root
      slave11:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/db1?useSSL=false
        username: root
        password: root
      slave12:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3308/db1?useSSL=false
        username: root
        password: root
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{id % 2}
      tables:
        t_user:
#          actualDataNodes: ds$->{0..1}.t_user$->{0..1}
#          tableStrategy:
#            inline:
#              shardingColumn: id
#              algorithmExpression: t_user$->{id % 2}
          keyGenerator:
            column: id
            type: SNOWFLAKE
      default-data-source-name: ds0
      master-slave-rules:
        ds0:
          master-data-source-name: ds0
          slave-data-source-names: slave01, slave02
        ds1:
          master-data-source-name: ds1
          slave-data-source-names: slave11, slave12
    props:
      sql:
        show: true



# 其他ShardingSphere配置
