version: '3.8'

networks:
  default:
    name: docker-mysql
    external: true

services:
  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: canal-server
    ports:
      - 11111:11111
    volumes:
#      - ./canal/conf:/home/admin/canal-server/conf
      - ./TmpData/canal/logs/:/home/admin/canal-server/logs/
    privileged: true
    environment:
      - canal.instance.mysql.slaveId=12   # slaveId 不与其他重复即可
      - canal.auto.scan=false                # 自动扫描
      - canal.destinations=canal_test         #  client 需要指定此 dest
      - canal.instance.master.address=mysql:3306   # mysql 地址
      - canal.instance.dbUsername=canal               # mysql username
      - canal.instance.dbPassword=canal       # mysql 密码
      - canal.instance.connectionCharset=UTF-8
      - canal.mq.topic=test
      - canal.instance.filter.regex=canalDB.canal_test
    depends_on:
      master:
        condition: service_healthy