apiVersion: v1
kind: Pod
metadata:
  name: localtime-same-with-host
  namespace: dev
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "sh", "-c", "date" ]
      volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
  volumes:
    - name: localtime
      hostPath:
        path: /etc/localtime  # 宿主机上的时区设置
  restartPolicy: Never