apiVersion: v1
kind: Pod
metadata:
  name: timezone-test
  namespace: dev
spec:
  containers:
    - name: test-container
      image: busybox
      command: [ "sh", "-c", "date" ]
      env:
        - name: TZ
          value: "America/Los_Angeles"  # 设置为你想要的时区
  restartPolicy: Never