version: '3'
services:
  master1:
    image: mysql:5.7
    container_name: mysql-master1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SERVER_ID: 1
      TZ: Asia/Shanghai
    entrypoint: /root/start.sh
    volumes:
      - ./TmpData/mysql/master1/data:/var/lib/mysql
      - ./TmpData/mysql/master1/log:/var/log/mysql
      - ./mysql/master1-conf/:/etc/mysql/conf.d/source
      - ./mysql/custom-entry/start.sh:/root/start.sh
      - ./mysql/master1-init/:/docker-entrypoint-initdb.d/
    hostname: master1
    networks:
      - mysql-network
    ports:
      - "3306:3306"

  master1-slave1:
    image: mysql:5.7
    container_name: mysql-master1-slave1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SERVER_ID: 2
      TZ: Asia/Shanghai
    entrypoint: /root/start.sh
    volumes:
      - ./TmpData/mysql/master1-slave1/data:/var/lib/mysql
      - ./TmpData/mysql/master1-slave1/log:/var/log/mysql
      - ./mysql/master1-slave1-conf/:/etc/mysql/conf.d/source
      - ./mysql/custom-entry/start.sh:/root/start.sh
    hostname: master1-slave1
    networks:
      - mysql-network
    ports:
      - "3307:3306"

  master1-slave2:
    image: mysql:5.7
    container_name: mysql-master1-slave2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SERVER_ID: 3
      TZ: Asia/Shanghai
    entrypoint: /root/start.sh
    volumes:
      - ./TmpData/mysql/master1-slave2/data:/var/lib/mysql
      - ./TmpData/mysql/master1-slave2/log:/var/log/mysql
      - ./mysql/master1-slave2-conf/:/etc/mysql/conf.d/source
      - ./mysql/custom-entry/start.sh:/root/start.sh
    hostname: master1-slave2
    networks:
      - mysql-network
    ports:
      - "3308:3306"

  canal-server:
    image: canal/canal-server:v1.1.5
    hostname: canal-server
    container_name: canal-server
    ports:
      - 11111:11111
    volumes:
      #      - ./canal/conf:/home/admin/canal-server/conf
      - ./TmpData/mysql/canal/canal-server-logs/:/home/admin/canal-server/logs/
    privileged: true
    environment:
      - canal.instance.mysql.slaveId=4   # slaveId 不与其他重复即可
      - canal.auto.scan=false                # 自动扫描
      - canal.destinations=test         #  client 需要指定此 dest
      - canal.instance.master.address=master1:3306   # mysql 地址
      - canal.instance.dbUsername=canal               # mysql username
      - canal.instance.dbPassword=canal       # mysql 密码
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.filter.regex=db0.t_user,db1.t_user
#      - canal.mq.topic=db01
      - canal.serverMode = rabbitMQ
      - rabbitmq.host = rabbitmq-node1
      - rabbitmq.virtual.host = /
      - rabbitmq.exchange = mysql.exchange
      - rabbitmq.username = guest
      - rabbitmq.password = guest
      - rabbitmq.deliveryMode = fanout
    depends_on:
      - master1
      - rabbitmq-node1
    links:
      - master1
      - rabbitmq-node1
    networks:
      - mysql-network

  my-config-server:
    image: config-server:v1.0
    container_name: my-config-server
    hostname: my-config-server
    networks:
      - mysql-network

networks:
  mysql-network: