version: "3.9"
services:
  rabbit1:
    image: rabbitmq:3.9.5-management-alpine
    hostname: rabbit1
    container_name: rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_NODENAME: rabbit1
    volumes:
      - ./TmpData/rabbitmq/data:/var/lib/rabbitmq
      - ./mq:/root/mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      rabbitmq-cluster:

  rabbit2:
    image: rabbitmq:3.9.5-management-alpine
    hostname: rabbit2
    container_name: rabbit2
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_NODENAME: rabbit2
    volumes:
      - ./TmpData/rabbitmq/data:/var/lib/rabbitmq
      - ./mq:/root/mq
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      rabbitmq-cluster:

  rabbit3:
    image: rabbitmq:3.9.5-management-alpine
    hostname: rabbit3
    container_name: rabbit3
    depends_on:
      - rabbit1
    environment:
      RABBITMQ_ERLANG_COOKIE: "cookie"
      RABBITMQ_NODENAME: rabbit3
    volumes:
      - ./TmpData/rabbitmq/data:/var/lib/rabbitmq
      - ./mq:/root/mq
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      rabbitmq-cluster:

networks:
  rabbitmq-cluster: