version: "3.9"
services:
  docker-registry:
    container_name: docker-registry
    image: registry:latest
    ports:
      - "5000:5000"
    restart: always
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:5000"