version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    hostname: mysql-5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      canalsharp:
        ipv4_address: 172.20.0.2
    volumes:
      - ./mysql/custom-entry/start.sh:/root/start.sh
      - ./mysql/master1-conf/:/etc/mysql/conf.d/source
      - ./canal/mysql/data/:/var/lib/mysql/
      - ./canal/mysql/log:/var/log/mysql
      - ./canal/mysql-init/:/docker-entrypoint-initdb.d/
    entrypoint: /root/start.sh


  canal-server:
    image: canal/canal-server:v1.1.5
    container_name: canal-server
    ports:
      - 11111:11111
    volumes:
#      - ./canal/conf:/home/admin/canal-server/conf
      - ./canal/canal-server-logs/:/home/admin/canal-server/logs/
    privileged: true
    environment:
      - canal.instance.mysql.slaveId=12   # slaveId 不与其他重复即可
      - canal.auto.scan=false                # 自动扫描
      - canal.destinations=test         #  client 需要指定此 dest
      - canal.instance.master.address=172.20.0.2:3306   # mysql 地址
      - canal.instance.dbUsername=canal               # mysql username
      - canal.instance.dbPassword=canal       # mysql 密码
      - canal.instance.connectionCharset=UTF-8
      - canal.mq.topic=test
      - canal.instance.filter.regex=test.test
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      canalsharp:
        ipv4_address: 172.20.0.3

networks:
  canalsharp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16