version: '3'
services:
  master:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/master/conf:/etc/mysql/conf.d/
#      - ./mysql/master/init:/docker-entrypoint-initdb.d/
      - ./TmpData/mysql/master/data:/var/lib/mysql
      - ./TmpData/mysql/master/log:/var/log/mysql
    networks:
      - mysql-network
    ports:
      - "3306:3306"
    entrypoint: >
      /bin/sh -c "chmod 0444 /etc/mysql/conf.d/my.cnf
      && docker-entrypoint.sh mysqld"
    # 添加健康检查
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping","-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 2

  slave0:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/slave0/conf:/etc/mysql/conf.d
      - ./TmpData/mysql/slave0/data:/var/lib/mysql
      - ./TmpData/mysql/slave0/log:/var/log/mysql
    networks:
      - mysql-network
    entrypoint: >
      /bin/sh -c "chmod 0444 /etc/mysql/conf.d/my.cnf
      && docker-entrypoint.sh mysqld"
    ports:
      - "3307:3306"
    # 添加健康检查
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping","-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 2
    depends_on:
      master:
        condition: service_healthy

  slave1:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/slave1/conf:/etc/mysql/conf.d
      - ./TmpData/mysql/slave1/data:/var/lib/mysql
      - ./TmpData/mysql/slave1/log:/var/log/mysql
    networks:
      - mysql-network
    ports:
      - "3308:3306"
    entrypoint: >
      /bin/sh -c "chmod 0444 /etc/mysql/conf.d/my.cnf
      && docker-entrypoint.sh mysqld"
    # 添加健康检查
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping","-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 2
    depends_on:
      master:
        condition: service_healthy

  my-config-server:
    image: mysql:5.7.16
    volumes:
      - ./mysql/config-server/config-master-slave:/root/
      - ./TmpData/mysql/config-server/data:/var/lib/mysql
      - ./TmpData/mysql/config-server/log:/var/log/mysql
    networks:
      - mysql-network
    entrypoint: >
      /bin/sh -c "/root/set-sysn-and-create-db-table.sh 
      && tail -f /root/slave0.cnf"
    depends_on:
      slave0:
        condition: service_healthy
      slave1:
        condition: service_healthy

networks:
  mysql-network:
    driver: bridge