version: '2'
services:
  master1:
    extends:
      file: docker-compose-mysql.yaml
      service: master1

  master1-slave1:
    extends:
      file: docker-compose-mysql.yaml
      service: master1-slave1

  master1-slave2:
    extends:
      file: docker-compose-mysql.yaml
      service: master1-slave2

  my-config-server:
    extends:
      file: docker-compose-mysql.yaml
      service: my-config-server
    depends_on:
      - master1
      - master1-slave1
      - master1-slave2

  rabbitmq-node1:
    extends:
      file: docker-compose-rabbitmq.yaml
      service: rabbitmq-node1

  rabbitmq-node2:
    extends:
      file: docker-compose-rabbitmq.yaml
      service: rabbitmq-node2

  rabbitmq-node3:
    extends:
      file: docker-compose-rabbitmq.yaml
      service: rabbitmq-node3

  canal-server:
    extends:
      file: docker-compose-mysql.yaml
      service: master1-slave2
    environment:
      - canal.instance.mysql.slaveId=4   # slaveId 不与其他重复即可
      - canal.auto.scan=false                # 自动扫描
      - canal.destinations=test         #  client 需要指定此 dest
      - canal.instance.master.address=master1:3306   # mysql 地址
      - canal.instance.dbUsername=canal               # mysql username
      - canal.instance.dbPassword=canal       # mysql 密码
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.filter.regex=db0.t_user,db1.t_user
      - rabbitmq.host = rabbitmq-node1
      - rabbitmq.virtual.host = /
      - rabbitmq.exchange = mysql.exchange
      - rabbitmq.username = guest
      - rabbitmq.password = guest
      - rabbitmq.deliveryMode = fanout
    depends_on:
      - rabbitmq-node1
      - master1

networks:
  mysql-network:
  rabbitmq-network:
