services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    hostname: rabbitmq1
    volumes:
      - ./TempData/log/rabbitmq:/var/log/rabbitmq
      - ./TempData/lib/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "uniquecookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
      RABBITMQ_CLUSTER_NAME: "rabbit@rabbitmq1"