services:
  rabbitmq:
    # hostname is important; otherwise after each container restart data will be lost
    hostname: 'rabbitmq'
    image: rabbitmq:3.11.4-management
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_PLUGINS_DIR=/opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    volumes:
      - ./temp/data/:/var/lib/rabbitmq/mnesia
      - ./temp/log/:/var/log/rabbitmq/
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins:rw
      - ./plugins:/usr/lib/rabbitmq/plugins