services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "uniquecookie"
      RABBITMQ_NODENAME: "rabbit@rabbitmq1"
      RABBITMQ_CLUSTER_NAME: "rabbit@rabbitmq1"