apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-image-registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-image-registry
  template:
    metadata:
      labels:
        app: docker-image-registry
    spec:
      containers:
        - name: docker-image-registry
          image: registry:lastest  # 替换为你的镜像名称和标签
          ports:
            - containerPort: 5000