version: '3'
services:
  master:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./master/conf:/etc/mysql/conf.d/
#      - ./master/init:/docker-entrypoint-initdb.d/
      - ./TempData/master/data:/var/lib/mysql
      - ./TempData/master/log:/var/log/mysql
    ports:
      - "3306:3306"
    entrypoint: >
      /bin/sh -c "chmod 0444 /etc/mysql/conf.d/my.cnf
      && docker-entrypoint.sh mysqld"
    # 添加健康检查
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping","-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 2

  slave0:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./slave0/conf:/etc/mysql/conf.d
      - ./TempData/slave0/data:/var/lib/mysql
      - ./TempData/slave0/log:/var/log/mysql
    entrypoint: >
      /bin/sh -c "chmod 0444 /etc/mysql/conf.d/my.cnf
      && docker-entrypoint.sh mysqld"
    ports:
      - "3307:3306"
    # 添加健康检查
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping","-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 2
    depends_on:
      master:
        condition: service_healthy

  slave1:
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
    volumes:
      - ./slave1/conf:/etc/mysql/conf.d
      - ./TempData/slave1/data:/var/lib/mysql
      - ./TempData/slave1/log:/var/log/mysql
    ports:
      - "3308:3306"
    entrypoint: >
      /bin/sh -c "chmod 0444 /etc/mysql/conf.d/my.cnf
      && docker-entrypoint.sh mysqld"
    # 添加健康检查
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "ping","-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 2
    depends_on:
      master:
        condition: service_healthy

  my-config-server:
    image: mysql:5.7.16
    volumes:
      - ./config-server/config-master-slave:/root/
      - ./TempData/config-server/data:/var/lib/mysql
      - ./TempData/config-server/log:/var/log/mysql
    entrypoint: >
      /bin/sh -c "/root/set-sysn-and-create-db-table.sh
      "
#      --&& tail -f /root/slave0.cnf
    depends_on:
      slave0:
        condition: service_healthy
      slave1:
        condition: service_healthy