version: '3'
services:
  master:
    image: mariadb:10.8.3
    container_name: mariadb-master
    networks:
      fixed:
        ipv4_address: 172.1.0.2
    environment:
      MYSQL_ROOT_PASSWORD: master
      MYSQL_DATABASE: master-slave
      MYSQL_USER: master
      MYSQL_PASSWORD: master
    volumes:
      - ./master-data:/var/lib/mysql # 数据库文件
      - ./master-conf:/etc/mysql
    ports:
      - "3306:3306"

  slave:
    image: mariadb:10.8.3
    container_name: mariadb-slave
    networks:
      fixed:
        ipv4_address: 172.1.0.3
    environment:
      MYSQL_ROOT_PASSWORD: slave
    volumes:
      - ./slave-data:/var/lib/mysql
      - ./slave-conf:/etc/mysql
    ports:
      - "3307:3306"

networks:
  fixed:
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
