version: '3'
services:
  master:
    image: mysql-5.7
    container_name: mysql-master
    networks:
      fixed:
        ipv4_address: 172.1.0.2
    environment:
      MYSQL_ROOT_PASSWORD: master
      TZ: Asia/Shanghai
    volumes:
      - D:/docker-volume/mysql/master/data:/var/lib/mysql # 数据库文件
      - ./master-conf/:/etc/mysql/conf.d/source
    ports:
      - "3306:3306"

  slave:
    image: mysql-5.7
    container_name: mysql-slave
    networks:
      fixed:
        ipv4_address: 172.1.0.3
    environment:
      MYSQL_ROOT_PASSWORD: slave
      TZ: Asia/Shanghai
    volumes:
      - D:/docker-volume/mysql/slave/data:/var/lib/mysql
      - ./slave-conf/:/etc/mysql/conf.d/source
    ports:
      - "3307:3306"

networks:
  fixed:
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
