apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: dev
spec:
  schedule: "*/1 * * * *"  # 在每天的凌晨1点执行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-job-container
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo This is cron job example
          restartPolicy: OnFailure